### PR TITLE
Changes the default window dimensions to 1024x768

### PR DESCRIPTION
**Pull request by cugone**
Branches off #160. Only the last commit is new.

The parent branches fix the options menu such that any window size will work even, 640x480, but that's old school 90s support. This commit assumes you at least have a monitor from 2000.

### CODE REVIEW

**Comment by DanRStevens** [comment]
The base branch was merged, and then undone due to build problems. As such, this branch no longer has a stable base to build on top of. It may either need rework, or perhaps be dropped.

----

I've noticed the odd resolution parameters. I can understand the desire to change them. I wonder if they may have been chosen slightly smaller due to window border or task bar allowances. If the game is run in windowed mode, less than the full screen resolution will be available. @ldicker83, can you comment on this?

----

If the game defaults to windowed mode, maybe we shouldn't have a hardcoded constant for the default size. Maybe we should just try to run maximized, and work with whatever that is, assuming it's not less than some minimum. Though, considering you've successfully tested the game at 640x480, we probably won't be running into problems with a true minimum size restriction.

I assume there should be an easy enough way to determine a maximized size, for the current desktop resolution. I suggest dynamically determining the default initial size, for when the configuration settings don't specify one, or when they specify an invalid size.

**Comment by cugone** [comment]
> 
> If the game defaults to windowed mode, maybe we shouldn't have a hardcoded constant for the default size. Maybe we should just try to run maximized, and work with whatever that is, assuming it's not less than some minimum. Though, considering you've successfully tested the game at 640x480, we probably won't be running into problems with a true minimum size restriction.

This is an easy fix, though running maximized and NOT borderless sometimes causes graphical issues with the backbuffer sizes. Maybe the reason an odd resolution was chosen was because at the time figuring out how to create a borderless window was unknown.

> 
> I assume there should be an easy enough way to determine a maximized size, for the current desktop resolution. I suggest dynamically determining the default initial size, for when the configuration settings don't specify one, or when they specify an invalid size.

SDL and Windows both have functions for getting the current desktop size; forcing the default window to that size isn't hard. Again, should default to make it a borderless window.

**Comment by DanRStevens** [comment]
I would like to be able to play fullscreen borderless.

There would need to be a way to exit full screen. Currently window sizing is controlling by dragging the edges of the window, or with the minimize and maximize butters. If those are removed when going borderless, there will need to be some kind of replacement.

What is the specific code needed to determine full screen size with/without borders?

**Comment by cugone** [comment]
> What is the specific code needed to determine full screen size with/without borders?

See for SDL: https://wiki.libsdl.org/SDL_CreateWindow
Windows is a little more involved. Raymond Chen posted an example on his blog 10 years ago: https://devblogs.microsoft.com/oldnewthing/20100412-00/?p=14353

None of these methods resize the backbuffers so you will get stretching.

> There would need to be a way to exit full screen. Currently window sizing is controlling by dragging the edges of the window, or with the minimize and maximize butters. If those are removed when going borderless, there will need to be some kind of replacement.

The Windows API allows for disabling resizing a window via dragging. I don't know about SDL.

Windowed Fullscreen (borderless window the size of the desktop) is the convention these days. Exclusive Fullscreen on modern Windows provides no benefit. In fact, Windows 10 just gives you a Borderless Fullscreen window even if you ask for exclusive.

By default `ALT+ENTER` asks a window to toggle full screen. Cursory google searches say SDL does the same.

> I would like to be able to play fullscreen borderless.

Me too. See above. When I check Fullscreen in the options menu Windows 10 gives me a Borderless Fullscreen Window by default (I can tell because I can set breakpoints and the game doesn't take control my computer away from me.)

**Comment by DanRStevens** [comment]
Thank you for the reference links.

I don't mean to disable window resizing. I mean to enable it when there is no longer a border or buttons to click on.

Hotkeys can work, though if they're not intuitive, people could get stuck in fullscreen, and maybe they don't want to exit the game to access their desktop.

Currently on Linux the maximize button leaves the game in full screen windowed mode, and `<ALT>+<ENTER>` does nothing.

**Comment by cugone** [comment]
Generally, you only go borderless in a full screen context. Otherwise you leave the window borders and titlebar. In any case, using the options menu to select an appropriate Resolution is the conventional way to change the size of the window *because* it's assumed you have fullscreen turned on and have no way to access the maximize button or borders to drag.

**Comment by cugone** [comment]
Closing because this needs to be reworked. See #196 for a summary.

**Pull request closed without merging**
